import Head from 'next/head';
import Header from '../Header/Header';
import Footer from '../Footer/Footer'

const Layout = ({children, page}) => {
  return (
    <div >
      <Head>
        <title> Alba Portfolio - {page}</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
    
        <Header/>

        {children}

      <Footer/>
    </div>
  )
}

export default Layout